<?php

function get_acf_fields(){
  if( function_exists('acf_add_local_field_group') ): //'acf_add_local_field_group') ):
    return array (
      'key' => 'group_566b3e3a26be9',
      'title' => 'Schema',
      'fields' => array (
        array (
          'key' => 'field_53ffb96a736fd',
          'label' => 'Author',
          'name' => 'author',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'formatting' => 'html',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_5568fde26e742',
          'label' => 'Author url',
          'name' => 'author_url',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'formatting' => 'html',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_53ffb9b4e0cd4',
          'label' => 'Status',
          'name' => 'status',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'formatting' => 'html',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_5543cef04ea23',
          'label' => 'Organization',
          'name' => 'organization',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'formatting' => 'html',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_5522f4f1494dc',
          'label' => 'CLIME Approval',
          'name' => 'clime_approval',
          'type' => 'checkbox',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'choices' => array (
            'approved' => 'approved',
          ),
          'default_value' => array (
          ),
          'layout' => 'vertical',
          'toggle' => 0,
        ),
        array (
          'key' => 'field_53ffba0683468',
          'label' => 'Schema Versions',
          'name' => 'schema_versions',
          'type' => 'repeater',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'row_min' => 1,
          'row_limit' => '',
          'layout' => 'row',
          'button_label' => 'Add Row',
          'min' => 0,
          'max' => 0,
          'collapsed' => '',
          'sub_fields' => array (
            array (
              'key' => 'field_5527019e04549',
              'label' => 'Version',
              'name' => 'version',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'formatting' => 'none',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_552701f50454a',
              'label' => 'Visibility',
              'name' => 'visibility',
              'type' => 'checkbox',
              'instructions' => 'Make the schema version visible in the public-facing library',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'visible' => 'visible',
              ),
              'default_value' => array (
              ),
              'layout' => 'horizontal',
              'toggle' => 0,
            ),
            array (
              'key' => 'field_5527016704548',
              'label' => 'Schema JSON',
              'name' => 'schema_json',
              'type' => 'textarea',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'maxlength' => '',
              'rows' => '',
              'new_lines' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_56216c556c4e5',
              'label' => 'Released',
              'name' => 'released',
              'type' => 'date_picker',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'first_day' => 1,
              'return_format' => 'Ymd',
              'display_format' => 'm/d/Y',
            ),
          ),
        ),
        array (
          'key' => 'field_5537e16bd8454',
          'label' => 'Sample Data',
          'name' => 'sample_data',
          'type' => 'repeater',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'row_min' => '',
          'row_limit' => '',
          'layout' => 'row',
          'button_label' => 'Add Row',
          'min' => 0,
          'max' => 0,
          'collapsed' => '',
          'sub_fields' => array (
            array (
              'key' => 'field_55383916bb693',
              'label' => 'Version',
              'name' => 'version',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'formatting' => 'html',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_55383bab352b6',
              'label' => 'Visibility',
              'name' => 'visibility',
              'type' => 'checkbox',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'choices' => array (
                'visible' => 'visible',
              ),
              'default_value' => array (
              ),
              'layout' => 'horizontal',
              'toggle' => 0,
            ),
            array (
              'key' => 'field_5537e258d8455',
              'label' => 'Title',
              'name' => 'title',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'formatting' => 'html',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_5537e269d8456',
              'label' => 'Sample data JSON',
              'name' => 'sample_data_json',
              'type' => 'textarea',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'maxlength' => '',
              'rows' => '',
              'new_lines' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_55392c042a236',
              'label' => 'File Name',
              'name' => 'file_name',
              'type' => 'hidden',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'font_size' => 14,
            ),
            array (
              'key' => 'field_55392c1b2a237',
              'label' => 'Description',
              'name' => 'description',
              'type' => 'hidden',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'font_size' => 14,
            ),
          ),
        ),
        array (
          'key' => 'field_53ffba2df32d1',
          'label' => 'Datasources',
          'name' => 'datasources',
          'type' => 'wysiwyg',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'toolbar' => 'full',
          'media_upload' => 1,
          'tabs' => 'all',
        ),
        array (
          'key' => 'field_53ffba392f6cc',
          'label' => 'Related Information',
          'name' => 'related_information',
          'type' => 'wysiwyg',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'toolbar' => 'full',
          'media_upload' => 1,
          'tabs' => 'all',
        ),
        array (
          'key' => 'field_5522f544494dd',
          'label' => 'Contributors',
          'name' => 'contributors',
          'type' => 'repeater',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'row_min' => '',
          'row_limit' => '',
          'layout' => 'table',
          'button_label' => 'Add Row',
          'min' => 0,
          'max' => 0,
          'collapsed' => '',
          'sub_fields' => array (
            array (
              'key' => 'field_5522fb7b57ff7',
              'label' => 'Name',
              'name' => 'name',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'formatting' => 'html',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_5522fb8757ff8',
              'label' => 'Image url',
              'name' => 'image_url',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'formatting' => 'html',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_556b910aa44d4',
              'label' => 'Profile url',
              'name' => 'profile_url',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
            array (
              'key' => 'field_568f1c470db3e',
              'label' => 'URL',
              'name' => 'url',
              'type' => 'text',
              'instructions' => '',
              'required' => 0,
              'conditional_logic' => 0,
              'wrapper' => array (
                'width' => '',
                'class' => '',
                'id' => '',
              ),
              'default_value' => '',
              'placeholder' => '',
              'prepend' => '',
              'append' => '',
              'maxlength' => '',
              'readonly' => 0,
              'disabled' => 0,
            ),
          ),
        ),
        array (
          'key' => 'field_565df7c2d9507',
          'label' => 'Deprecated',
          'name' => 'deprecated',
          'type' => 'true_false',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 0,
        ),
      ),
      'location' => array (
        array (
          array (
            'param' => 'post_type',
            'operator' => '==',
            'value' => 'schema',
          ),
        ),
      ),
      'menu_order' => 0,
      'position' => 'normal',
      'style' => 'seamless',
      'label_placement' => 'top',
      'instruction_placement' => 'label',
      'hide_on_screen' => '',
      'active' => 1,
      'description' => '',
    );

  endif;
  return false;
}

?>